### ISSUE TITLE
Components - Create footer

### ISSUE THREAD

**Issue by Jesse-Kramer** [Jesse-Kramer/your-tribe-for-life-squad-page#13]
We willen een footer maken via een component. Hiervoor moet wel een design worden gemaakt. Pak inspiratie van het deisign van Jelte. https://www.figma.com/design/RzXYFnNmDgT5D6LNmNcXP0/Figma-design-squad-page?node-id=0-1&node-type=canvas&t=VITO4PIGvd5OUld9-0

**Comment by driezie** [comment]
Ik heb een review beoordeling gegeven. Het ziet er heel goed uit. Er zijn hierbij nog wel een paar kleine aanpassingen die ik wil aanpassen. Voor de rest goed gedaan!

#16 

- JC
