### ISSUE TITLE
Card Component aan Squad filter page

### ISSUE THREAD

**Issue by J3SS3HVA** [Jesse-Kramer/your-tribe-for-life-squad-page#19]
{userstory}: In de hoofd pagina heeft elke person een styling. het is de bedoeling dat Die styling een component word die card heet en dat hij op elke andere squad-page komt die gefilterd is op klas of jaar

**Comment by driezie** [comment]
Deze issue is deel van een grote issue #25 

Dit is 1 van de 3 componenten die hiernaar worden gedeeld
