### ISSUE TITLE
Testen / HTML Validator

### ISSUE THREAD

**Issue by driezie** [Jesse-Kramer/your-tribe-for-life-squad-page#24]
Maak gebruik van HTML Validator om te kijken of je website goed in elkaar zit.

[HTML Validator](https://validator.w3.org/)

### Zo niet?
Maak een issue aan en vergeet niet de issue te linken aan deze issue!

**Comment by Jesse-Kramer** [comment]
![Image](https://github.com/user-attachments/assets/dc80a22c-5f69-4641-9d97-681295b362f0)
De HTML validator is uitgevoerd. Hierbij hebben we dit opgelost door commit #dee0004
Fix #24
