### ISSUE TITLE
Feedback groep 3

### ISSUE THREAD

**Issue by EBok1** [Jesse-Kramer/your-tribe-for-life-squad-page#3]
We zien dat jullie een projectboard hebben gemaakt, maar hier nog niks in hebben gezet. 
Op de website kunnen we zien dat jullie een goede opzet hebben gemaakt. 
Maak gebruik van issues, zodat we jullie proces kunnen volgen (dlc)!
Goed dat de website al live staat. 

Als jullie het logo meerdere keren willen gebruiken is het goed om hiervan een component te maken, zo niet is dit een overbodig component. 

@christoph3r3w 
@Ebok1
@Daan654
@TristanKatte
@Jason2426
@annelinderaadsheer

**Comment by Jesse-Kramer** [comment]
Bedankt voor de feedback, we hebben het  verwerkt!
