### ISSUE TITLE
Readme klaar maken voor oplevering

### ISSUE THREAD

**Issue by Patrickkhr** [Jesse-Kramer/your-tribe-for-life-squad-page#30]
Een korte samenvatting van het project maken met daarin:

- CMS Uitleg
- Inhoudsopgave
- Beschrijving
- Gebruik
- Kenmerken
- Installatie
- Bronnen

**Comment by Jesse-Kramer** [comment]
![Image](https://github.com/user-attachments/assets/2070886b-8ba4-450f-acb5-03eb0a2bc171)
We hebben een duidelijke en nette readme gemaakt!
